# https://gist.github.com/thmsgbrt/9b22b836fb11167400e0e63f8c326fae#file-main-yaml
# https://medium.com/swlh/how-to-create-a-self-updating-readme-md-for-your-github-profile-f8b05744ca91
name: Build Readme

on:
    push:
        branches:
            - master
    schedule:
        # every two hours
        - cron: '0 */2 * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout current repository to Master branch
              uses: actions/checkout@v1
            - name: Setup NodeJs 16.14
              uses: actions/setup-node@v1
              with:
                  node-version: '16.14'
            - name: Cache dependencies and build outputs to improve workflow execution time.
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
            - name: Install dependencies
              run: npm install
            - name: Generate README file
              run: npm run updateGithubReadme
              env:
                  NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
            - name: Commit and Push new README.md to the repository
              uses: mikeal/publish-to-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
