name: Revalidate Mitchinson.dev

on:
    push:
        branches:
            - main
    schedule:
        # every two hours
        - cron: '0 */2 * * *'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout current repository
              uses: actions/checkout@v1
            - name: Setup NodeJs 16.14
              uses: actions/setup-node@v1
              with:
                  node-version: '16.14'
            - name: Cache dependencies and build outputs to improve workflow execution time.
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
            - name: Install dependencies
              run: npm install
            - name: Revalidate Mitchinson.dev
              run: npm run revalidateMitchinsonDev
              env:
                  REVALIDATE_PASS: ${{ secrets.REVALIDATE_PASS }}
                  NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
